---
- name: create install directory
  file: path=/usr/java state=directory
  tags:
    - java

- name: download tarball
  command: curl
    --location
    --header "Cookie:oraclelicense=accept-securebackup-cookie"
    --output /tmp/{{ java_tarball_file }}
    {{ java_tarball_url }}
  args:
    creates: /tmp/{{ java_tarball_file }}
  tags:
    - java

- name: unarchive tarball
  unarchive: src=/tmp/{{ java_tarball_file }} dest=/usr/java copy=no
  tags:
    - java

- name: link latest version
  file: src=/usr/java/jdk{{ java_version }} dest=/usr/java/latest state=link
  tags:
    - java

- name: link default version
  file: src=/usr/java/latest dest=/usr/java/default state=link
  tags:
    - java

- name: register java bin
  file: src=/usr/java/default/bin/java dest=/usr/bin/java state=link
